= GR8 CRM - Custom Properties Plugin
Göran Ehrsson <goran@technipelago.se>
:description: Official documentation for the GR8 CRM Custom Properties Plugin
:keywords: groovy, grails, crm, gr8crm, documentation
:toc:
:numbered:
:icons: font
:imagesdir: ./images
:source-highlighter: prettify
:homepage: http://gr8crm.github.io
:gr8crm: GR8 CRM
:gr8source: https://github.com/technipelago/grails-crm-property
:license: This plugin is licensed with http://www.apache.org/licenses/LICENSE-2.0.html[Apache License version 2.0]

== Introduction

{gr8crm} is a set of http://www.grails.org/[Grails Web Application Framework]
plugins that makes it easy to develop web applications with CRM functionality.

You can find more information about {gr8crm} on the main documentation site {homepage}.

=== Customer Relationship Management

Customer relationship management (CRM) is a system for managing a company’s interactions with current and future customers.
It involves using technology to organize, automate and synchronize sales, marketing, customer service, and technical support.
http://en.wikipedia.org/wiki/Customer_relationship_management[Wikipedia]

The {gr8crm} "Ecosystem" currently contains over 40 Grails plugins. For a complete list of plugins see {homepage}.

Each {gr8crm} plugin defines a http://martinfowler.com/bliki/BoundedContext.html[Bounded Context]
that focus on one specific domain, for example *contact*, *project* or *document*.

=== Custom Properties Plugin

This plugin makes is possible for an application super-user to define custom properties for domain classes.
A custom property can be of type *string*, *number* and *date*.

== Add custom properties

Two user-facing views are provided by the plugin. One displayed in the show-contact view and one displayed in the edit-contact view.
The views are not added automatically but you can easily add them in BootStrap.groovy for your application.

The following code snippet adds custom property views to the contact views (company, person, etc.)

[source,groovy]
----
class BootStrap {

    def crmPluginService
    def crmCoreService
    def crmPropertyService

    def init = { servletContext ->
        // Add custom property tab to show contact page.
        crmPluginService.registerView('crmContact', 'show', 'tabs',
                [id: "props", index: 120, label: "Properties", template: '/crmProperty/show', plugin: "crm-property", model: {
                    def rid = crmCoreService.getReferenceIdentifier(crmContact)
                    def result = crmPropertyService.getConfigs('crmContact')
                    def values = crmPropertyService.getValues(crmContact)
                    return [bean: crmContact, reference: rid, result: result, totalCount: values.size()]
                }]
        )
        // Add custom property tab to edit contact page.
        crmPluginService.registerView('crmContact', 'edit', 'tabs',
                [id: "props", index: 120, label: "Properties", template: '/crmProperty/edit', plugin: "crm-property", model: {
                    def rid = crmCoreService.getReferenceIdentifier(crmContact)
                    def result = crmPropertyService.getConfigs('crmContact')
                    def values = crmPropertyService.getValues(crmContact)
                    return [bean: crmContact, reference: rid, result: result, totalCount: values.size()]
                }]
        )
    }
}
----

== CrmPropertyService

The `crmPropertyService` bean provides methods for configuring and working with custom property values.

[source,groovy]
----
crmPropertyService.createStringConfig(CrmContact, "team", "Team name")
crmPropertyService.createNumberConfig(CrmContact, "weight", "Weight (kg)")
crmPropertyService.createDateConfig(CrmContact, "birthDate", "Birth date")
----


== Instance methods

Each domain class that has a static property called `customProperties` will have instance methods for setting and getting custom property values.

[source,groovy]
----
def person = CrmContact.findByName("Mr Groovy")

person.setCustomProperty('team', 'Grails')
person.setCustomProperty('weight', 82)
person.setCustomProperty('birthDate', '1992-05-23')


----


== Changes

2.4.0:: First public release

== License

{license}

== Source Code

The source code for this plugin is available at {gr8source}

== Contributing

Please report {gr8source}/issues[issues or suggestions].

Want to improve the plugin: Fork the {gr8source}[repository] and send a pull request.
